// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SnippetPackVsix
{
    static class Vsix
    {
        public const string Id = "06c238e3-b879-4278-b1d9-4804e14276e3";
        public const string Name = "Snippet Pack Project Template";
        public const string Description = "A Visual Studio project template for creating code snippet packs targeting any supported language. The snippet pack will be an extension you can share with your team or upload to the Visual Studio extension gallery.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "snippets, extension";
    }
}
